version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.8.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/backend:/mlflow/backend
      - ./mlflow/artifacts:/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/backend/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"


  api:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: ml_api
    ports:
      - "4028:4028"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow
